version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      # Mount the local SQLite database file into the container
      # Ensure this path matches the one derived from DATABASE_URL in your .env
      - ./aeroscout.db:/app/aeroscout.db
      # Mount the cookie cache file
      # Ensure this path matches TRIP_COOKIE_FILE in your .env
      - ./trip_cookies.json:/app/trip_cookies.json
      # Mount the token cache file
      # Ensure this path matches KIWI_TOKEN_FILE in your .env
      - ./kiwi_token.json:/app/kiwi_token.json
      # Mount the application code for development hot-reloading
      # For production, remove this volume mount and the --reload flag below
      - ./app:/app/app
    env_file:
      - .env
    # Command to run the application with auto-reload (for development)
    # For production, remove the --reload flag
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload